MvcLesson1/MvcLesson1/Models/Department.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcLesson1.Models
{
    [Table("tblDepartment")]
    public class Department
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public List<Employee> Employees { get; set; }
    }
}

MvcLesson1/MvcLesson1/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcLesson1.Models
{
    [Table("tblEmployee")]
    public class Employee
    {
        public int employeeId { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public int departmentID { get; set; }
    }
}

MvcLesson1/MvcLesson1/Models/EmployeeContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace MvcLesson1.Models
{
    public class EmployeeContext : DbContext
    {
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Department> Departments { get; set; }
    }
}

MvcLesson1/MvcLesson1/Controllers/BsEmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer;

namespace MvcLesson1.Controllers
{
    public class BsEmployeeController : Controller
    {
        public ActionResult Index()
        {
            EmployeeBusinessLayer employeeBusinessLayer = new EmployeeBusinessLayer();
            List<EmployeeC1> employees = employeeBusinessLayer.Employees.ToList();
            return View(employees);
        }

        [HttpGet]
        [ActionName("Create")]
        public ActionResult Create_Get()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Create")]
        public ActionResult Create_Post(EmployeeC1 employee)
        {
                //EmployeeC1 employee = new EmployeeC1();
                //TryUpdateModel(employee);

            if (ModelState.IsValid)
            {
                EmployeeBusinessLayer employeeBusinessLayer = new EmployeeBusinessLayer();

                employeeBusinessLayer.AddEmployee(employee);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        [ActionName("Edit")]
        public ActionResult Edit_Get(int id)
        {
            EmployeeBusinessLayer employeeBusinessLayer = new EmployeeBusinessLayer();
            EmployeeC1 employee = employeeBusinessLayer.Employees.Single(emp => emp.employeeId == id);
            return View(employee);
        }

        [HttpPost]
        [ActionName("Edit")]
        public ActionResult Edit_Post(int id)
        {
            EmployeeBusinessLayer employeeBusinessLayer = new EmployeeBusinessLayer();
            EmployeeC1 employee = employeeBusinessLayer.Employees.Single(x => x.employeeId == id);
            UpdateModel(employee, null, null, new string[] { "employeeId" });

            if (ModelState.IsValid)
            {
                employeeBusinessLayer.SaveEmployee(employee);

                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            EmployeeBusinessLayer employeeBusinessLayer = new EmployeeBusinessLayer();
            employeeBusinessLayer.DeleteEmployee(id);
            return RedirectToAction("Index");
        }

    }
}

MvcLesson1/MvcLesson1/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcLesson1.Models;

namespace MvcLesson1.Controllers
{
    public class DepartmentController : Controller
    {
        public ActionResult Index()
        {
            EmployeeContext employeeContext = new EmployeeContext();
            List<Department> departments = employeeContext.Departments.ToList();

            return View(departments);
        }

    }
}

MvcLesson1/MvcLesson1/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcLesson1.Models;

namespace MvcLesson1.Controllers
{
    public class EmployeeController : Controller
    {
        public ActionResult Index(int deptId)
        {
            EmployeeContext employeeContext = new EmployeeContext();
            List<Employee> employees = employeeContext.Employees.Where(emp => emp.departmentID == deptId).ToList();
            return View(employees);
        }

        public ActionResult Details(int id)
        {
            EmployeeContext employeeContext = new EmployeeContext();
            Employee employee = employeeContext.Employees.Single(emp => emp.employeeId == id);
            return View(employee);
        }
    }
}

MvcLesson1/MvcLesson1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcLesson1.Controllers
{
    public class HomeController : Controller
    {
        public ViewResult Index()
        {
            ViewData["Products"] = new List<string>()
            {
                "Mobile",
                "Watch",
                "Notebook",
                "T-shirt",
                "Sandels"
            };
            return View();
        }

        public string GetDetails(string name, string id)
        {
            return "Product Name: " + name + "<br />ID: " + id;
        }

    }
}

MvcLesson1/MvcLesson1/Views/BsEmployee/Create.cshtml
@model BusinessLayer.EmployeeC1

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Add New Employee</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.name)
            @Html.ValidationMessageFor(model => model.name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.city)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.city)
            @Html.ValidationMessageFor(model => model.city)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateOfBirth)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateOfBirth)
            @Html.ValidationMessageFor(model => model.DateOfBirth)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MvcLesson1/MvcLesson1/Views/BsEmployee/Edit.cshtml
@model BusinessLayer.EmployeeC1

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Employee Edit</legend>
        
        
        <div class="editor-label">
            @Html.LabelFor(model => model.employeeId)
        </div>
        <div class="editor-field">
            @Html.DisplayFor(model => model.employeeId)
            @Html.HiddenFor(Model => Model.employeeId)
            @Html.ValidationMessageFor(model => model.employeeId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.name)
            @Html.ValidationMessageFor(model => model.name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.city)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.city)
            @Html.ValidationMessageFor(model => model.city)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateOfBirth)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateOfBirth)
            @Html.ValidationMessageFor(model => model.DateOfBirth)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


MvcLesson1/MvcLesson1/Views/BsEmployee/Index.cshtml
@model IEnumerable<BusinessLayer.EmployeeC1>

@{
    ViewBag.Title = "Index";
}
<h2>Index</h2>

<div style="font-family: sans-serif;">
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table border="1" cellpadding="5" cellspacing="0" style="font-size: 13px">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.employeeId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.city)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </th>
            <th>Actions</th>
        </tr>

        @foreach (var item in Model)
        {
            using(Html.BeginForm("Delete", "BsEmployee", new { id = item.employeeId }))
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.employeeId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.city)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfBirth)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.employeeId }) |
                    <input type="submit" value="Delete" onclick="return confirm('Are you sure you want to delete record of @item.name    ');" />
                </td>
            </tr>
            }
        }

    </table>
</div>

MvcLesson1/MvcLesson1/Views/Department/Index.cshtml
@using MvcLesson1.Models;

@model IEnumerable<Department>

@{
    ViewBag.Title = "Department List";
}
<div style="font-family:sans-serif">

<h2>Department List</h2>
    <ul>
        @foreach (Department dept in @Model)
        {
            <li>@Html.ActionLink(dept.Name, "Index", "Employee", new { deptId = dept.ID }, null)</li>
        }
    </ul>
</div>

MvcLesson1/MvcLesson1/Views/Employee/Details.cshtml
@model MvcLesson1.Models.Employee

@{
    ViewBag.Title = "Employee Details";
}
<div>

<h2>Employee Details</h2>
<table border="1" cellpadding="5" cellspacing="0">
    <thead>
        <tr>
            <th>Employee ID</th>
            <th>Name</th>
            <th>City</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Model.employeeId</td>
            <td>@Model.name</td>
            <td>@Model.city</td>
        </tr>
    </tbody>
</table>
<br />
    @Html.ActionLink("Back to Employee List", "Index", new { deptID = @Model.departmentID })
</div>

MvcLesson1/MvcLesson1/Views/Employee/Index.cshtml
@model IEnumerable<MvcLesson1.Models.Employee>

@using MvcLesson1.Models;

@{
    ViewBag.Title = "Employee List";
}

<div style="font-family:sans-serif">


<h2>Employee List</h2>

    <ul>
        @foreach (Employee emp in @Model)
        { 
        <li>@Html.ActionLink(emp.name,"Details", new {@id=emp.employeeId})</li>
        }
    </ul>
    
<br />
    @Html.ActionLink("Back to Department List", "Index", "Department");
</div>

MvcLesson1/MvcLesson1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Products | Home";
}

<h2>Product List</h2>
<ul>
    @foreach (string name in (List<string>)ViewData["Products"])
    { 
    <li>@name</li>
    }
</ul>